trigger:
  - main

pr:
  - main

pool: "self-hosted"

steps:
  - checkout: self
    fetchDepth: 0
  - task: DotNetCoreCLI@2
    name: Restore
    inputs:
      command: 'restore'
      arguments: '-c Release'
  - task: DotNetCoreCLI@2
    displayName: "Build project"
    inputs:
      command: 'build'
      arguments: '-c Release'
  - task: DotNetCoreCLI@2
    displayName: "Run tests"
    inputs:
      command: 'test'
      projects: 'tests/Splitwise.Tests.Unit/Splitwise.Tests.Unit.csproj'
      arguments: '-c Release --collect:"XPlat Code Coverage"'
  - task: DotNetCoreCLI@2
    displayName: "Pack project into NuGet package"
    inputs:
      command: 'pack'
      packagesToPack: '**/Splitwise.csproj'
      versioningScheme: 'off'
      arguments: '-c Release -o $(Build.ArtifactStagingDirectory)'
  - task: PublishPipelineArtifact@1
    displayName: "Publish artifacts"
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'lib'